export default [
   'strapi::errors',
   {
      name: 'strapi::security',
      config: {
         contentSecurityPolicy: {
            useDefaults: true,
            directives: {
               'connect-src': ["'self'", 'https:', 'http:'],
               'img-src': ["'self'", 'data:', 'blob:', 'https:', 'http:'],
               'media-src': ["'self'", 'data:', 'blob:', 'https:', 'http:'],
               'frame-src': ["'self'", 'data:', 'blob:', 'https:', 'http:'],
               'default-src': ["'self'", 'https:', 'http:', 'data:', 'blob:'],
               'object-src': ["'self'", 'data:', 'blob:', 'https:', 'http:'],
            },
         },
         cors: {
            enabled: true,
            origin: ['https://localhossst:3000'],
            methods: [
               'GET',
               'POST',
               'PUT',
               'PATCH',
               'DELETE',
               'HEAD',
               'OPTIONS',
            ],
            headers: [
               'Content-Type',
               'Authorization',
               'Origin',
               'Accept',
               'Content-Disposition',
               'Range',
            ],
            exposeHeaders: [
               'Content-Range',
               'Content-Length',
               'Content-Disposition',
            ],
            maxAge: 31536000,
            credentials: true,
         },
      },
   },
   'strapi::cors',
   'strapi::poweredBy',
   'strapi::logger',
   'strapi::query',
   'strapi::body',
   'strapi::session',
   'strapi::favicon',
   'strapi::public',
];
