services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myportfolio-web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local